/**
 * @file delta_es.h
 * 
 * @brief definition for the spanish language version of the delta keyboard
 *
 * Created on Wed Mar 10 2021
 *
 * Copyright (c) 2021 CmPi
 *
 */

#include <Arduino.h>

/**
 * Numpad keys definition (to send ALT + numbers)
 */

#define KEY_NON 0x00 // No key

#define KEY_KP1 0x59 // Keypad 1 and End
#define KEY_KP2 0x5a // Keypad 2 and Down Arrow
#define KEY_KP3 0x5b // Keypad 3 and PageDn
#define KEY_KP4 0x5c // Keypad 4 and Left Arrow
#define KEY_KP5 0x5d // Keypad 5
#define KEY_KP6 0x5e // Keypad 6 and Right Arrow
#define KEY_KP7 0x5f // Keypad 7 and Home
#define KEY_KP8 0x60 // Keypad 8 and Up Arrow
#define KEY_KP9 0x61 // Keypad 9 and Page Up
#define KEY_KP0 0x62 // Keypad 0 and Ins

/*
 * conversion touch => PIN
 */

#define TOUCHS_NUM 10
uint8_t aButtonsPin[TOUCHS_NUM] { 4, 0, 2, 15, 13, 12, 14, 27, 33, 32  }; 

#define NUM_MODIFIERS 2 

// Key to select 2nd character - 1st modifier 
#define DKEY_LEFT_TOUCH 6 

// Key to select 3rd character - 2nd modifier
#define DKEY_RIGHT_TOUCH 8 

#define KEYS_NUM 5 // number of keys (not counting modifiers)

// touch index                         0  1  2  3  4  5  6  7  8  9
uint8_t aTouchToSequence[TOUCHS_NUM] { 4, 3, 0, 0, 0, 5, 0, 2, 0, 1 }; // numbers from 1 to KEYS_NUM - 0 if not connected or not a sequence

// Touch 

// the first button, aButtonsPin[0] is the "modifier"
// the others buttons correspond to the following characters (x2 because of the modifier)



//  aButtonsPin[TOUCHS_NUM] { 04, xx, 02, xx, xx, 12, xx, 17, xx, 32  };



Sequence aSequence[(NUM_MODIFIERS==2?1:0)+KEYS_NUM*(1+NUM_MODIFIERS)] = {

    // Key 1 - no modifier
    { KEY_KP1, KEY_KP6, KEY_KP0, KEY_NON, KEY_NON, KEY_NON }, // ALT  160 - á - letter to be generated by aButtonsPin[1]
    // Key 2 - no modifier
    { KEY_KP1, KEY_KP3, KEY_KP0, KEY_NON, KEY_NON, KEY_NON }, // ALT  130 - é
    // Key 3 - no modifier
    { KEY_KP1, KEY_KP6, KEY_KP1, KEY_NON, KEY_NON, KEY_NON }, // ALT  161 - í
    // Key 4 - no modifier
    { KEY_KP1, KEY_KP6, KEY_KP2, KEY_NON, KEY_NON, KEY_NON }, // ALT  162 - ó
    // Key 5 - no modifier
    { KEY_KP1, KEY_KP6, KEY_KP4, KEY_NON, KEY_NON, KEY_NON }, // ALT  164 - ñ

    // Key 1 - 1st modifier
    { KEY_KP0, KEY_KP1, KEY_KP9, KEY_KP3, KEY_NON, KEY_NON }, // ALT 0193 - Á - letter to be generated by aButtonsPin[1] AND - letter to be generated by aButtonsPin[0]
    // Key 2 - 1st modifier
    { KEY_KP0, KEY_KP2, KEY_KP0, KEY_KP1, KEY_NON, KEY_NON }, // ALT 0201 - É
    // Key 3 - 1st modifier
    { KEY_KP0, KEY_KP2, KEY_KP0, KEY_KP5, KEY_NON, KEY_NON }, // ALT 0205 - Í
    // Key 4 - 1st modifier
    { KEY_KP0, KEY_KP2, KEY_KP1, KEY_KP1, KEY_NON, KEY_NON }, // ALT 0211 - Ó
    // Key 5 - 1st modifier
    { KEY_KP1, KEY_KP6, KEY_KP5, KEY_NON, KEY_NON, KEY_NON }, // ALT  165 - Ñ

    // Key 1 - 2nd modifier
    { KEY_KP0, KEY_KP1, KEY_KP9, KEY_KP1, KEY_NON, KEY_NON }, // ALT 0191 - ¿
    // Key 2 - 2nd modifier
    { KEY_KP0, KEY_KP1, KEY_KP6, KEY_KP1, KEY_NON, KEY_NON }, // ALT 0161 - ¡ - letter to be generated by aButtonsPin[8]
    // Key 3 - 2nd modifier
    { KEY_KP1, KEY_KP6, KEY_KP3, KEY_NON, KEY_NON, KEY_NON }, // ALT  163 - ú
    // Key 4 - 2nd modifier
    { KEY_KP0, KEY_KP2, KEY_KP1, KEY_KP8, KEY_NON, KEY_NON }, // ALT 0218 - Ú
    // Key 5 - 2nd modifier
    { KEY_KP0, KEY_KP2, KEY_KP5, KEY_KP2, KEY_NON, KEY_NON },  // ALT 0252 - ü

    // Key for 2 modifiers together
    { KEY_KP0, KEY_KP2, KEY_KP2, KEY_KP0, KEY_NON, KEY_NON }  // ALT 0220 - Ü
};

