/*
 * config.h
 *
 * Created on Mon Mar 08 2021
 *
 * The MIT License (MIT)
 * Copyright (c) 2021 CmPi
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial
 * portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */


#define TOUCHS_NUM 10

// the first button, aButtonsPin[0] is the "modifier"
// the others buttons correspond to the following characters (x2 because of the modifier)

uint8_t aButtonsPin[TOUCHS_NUM] { 2, 4, 0, 15, 13, 12, 14, 27, 33, 32 };

#define KEY_NON 0x00 // No key

#define KEY_KP1 0x59 // Keypad 1 and End
#define KEY_KP2 0x5a // Keypad 2 and Down Arrow
#define KEY_KP3 0x5b // Keypad 3 and PageDn
#define KEY_KP4 0x5c // Keypad 4 and Left Arrow
#define KEY_KP5 0x5d // Keypad 5
#define KEY_KP6 0x5e // Keypad 6 and Right Arrow
#define KEY_KP7 0x5f // Keypad 7 and Home
#define KEY_KP8 0x60 // Keypad 8 and Up Arrow
#define KEY_KP9 0x61 // Keypad 9 and Page Up
#define KEY_KP0 0x62 // Keypad 0 and Ins

Sequence aSequence[16] = {
    { KEY_KP1, KEY_KP6, KEY_KP0, KEY_NON, KEY_NON, KEY_NON }, // ALT  160 - á - letter to be generated by aButtonsPin[1]
    { KEY_KP1, KEY_KP3, KEY_KP0, KEY_NON, KEY_NON, KEY_NON }, // ALT  130 - é
    { KEY_KP1, KEY_KP6, KEY_KP1, KEY_NON, KEY_NON, KEY_NON }, // ALT  161 - í
    { KEY_KP1, KEY_KP6, KEY_KP2, KEY_NON, KEY_NON, KEY_NON }, // ALT  162 - ó
    { KEY_KP1, KEY_KP6, KEY_KP3, KEY_NON, KEY_NON, KEY_NON }, // ALT  163 - ú
    { KEY_KP1, KEY_KP6, KEY_KP4, KEY_NON, KEY_NON, KEY_NON }, // ALT  164 - ñ
    { KEY_KP0, KEY_KP1, KEY_KP9, KEY_KP1, KEY_NON, KEY_NON }, // ALT 0191 - ¿
    { KEY_KP0, KEY_KP1, KEY_KP6, KEY_KP1, KEY_NON, KEY_NON }, // ALT 0161 - ¡ - letter to be generated by aButtonsPin[8]
    { KEY_KP0, KEY_KP1, KEY_KP9, KEY_KP3, KEY_NON, KEY_NON }, // ALT 0193 - Á - letter to be generated by aButtonsPin[1] AND - letter to be generated by aButtonsPin[0]
    { KEY_KP0, KEY_KP2, KEY_KP0, KEY_KP1, KEY_NON, KEY_NON }, // ALT 0201 - É
    { KEY_KP0, KEY_KP2, KEY_KP0, KEY_KP5, KEY_NON, KEY_NON }, // ALT 0205 - Í
    { KEY_KP0, KEY_KP2, KEY_KP1, KEY_KP1, KEY_NON, KEY_NON }, // ALT 0211 - Ó
    { KEY_KP0, KEY_KP2, KEY_KP1, KEY_KP8, KEY_NON, KEY_NON }, // ALT 0218 - Ú
    { KEY_KP1, KEY_KP6, KEY_KP5, KEY_NON, KEY_NON, KEY_NON }, // ALT  165 - Ñ
    { KEY_KP0, KEY_KP2, KEY_KP5, KEY_KP2, KEY_NON, KEY_NON }, // ALT 0252 - ü
    { KEY_KP0, KEY_KP2, KEY_KP2, KEY_KP0, KEY_NON, KEY_NON }  // ALT 0220 - Ü
};
